/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedCarteirasRouteImport } from './routes/_authenticated/carteiras'
import { Route as AuthenticatedComiteRouteImport } from './routes/_authenticated/comite'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedFecharMesRouteImport } from './routes/_authenticated/fechar-mes'
import { Route as AuthenticatedFluxoDeCaixaRouteImport } from './routes/_authenticated/fluxo-de-caixa'
import { Route as AuthenticatedUploadsRouteImport } from './routes/_authenticated/uploads'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin/usuarios'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCarteirasRoute = AuthenticatedCarteirasRouteImport.update({
  id: '/carteiras',
  path: '/carteiras',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedComiteRoute = AuthenticatedComiteRouteImport.update({
  id: '/comite',
  path: '/comite',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFecharMesRoute = AuthenticatedFecharMesRouteImport.update({
  id: '/fechar-mes',
  path: '/fechar-mes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFluxoDeCaixaRoute =
  AuthenticatedFluxoDeCaixaRouteImport.update({
    id: '/fluxo-de-caixa',
    path: '/fluxo-de-caixa',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUploadsRoute = AuthenticatedUploadsRouteImport.update({
  id: '/uploads',
  path: '/uploads',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/admin/usuarios',
    path: '/admin/usuarios',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/carteiras': typeof AuthenticatedCarteirasRoute
  '/comite': typeof AuthenticatedComiteRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fechar-mes': typeof AuthenticatedFecharMesRoute
  '/fluxo-de-caixa': typeof AuthenticatedFluxoDeCaixaRoute
  '/uploads': typeof AuthenticatedUploadsRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/carteiras': typeof AuthenticatedCarteirasRoute
  '/comite': typeof AuthenticatedComiteRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fechar-mes': typeof AuthenticatedFecharMesRoute
  '/fluxo-de-caixa': typeof AuthenticatedFluxoDeCaixaRoute
  '/uploads': typeof AuthenticatedUploadsRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/carteiras': typeof AuthenticatedCarteirasRoute
  '/_authenticated/comite': typeof AuthenticatedComiteRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/fechar-mes': typeof AuthenticatedFecharMesRoute
  '/_authenticated/fluxo-de-caixa': typeof AuthenticatedFluxoDeCaixaRoute
  '/_authenticated/uploads': typeof AuthenticatedUploadsRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/carteiras'
    | '/comite'
    | '/dashboard'
    | '/fechar-mes'
    | '/fluxo-de-caixa'
    | '/uploads'
    | '/admin/usuarios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/carteiras'
    | '/comite'
    | '/dashboard'
    | '/fechar-mes'
    | '/fluxo-de-caixa'
    | '/uploads'
    | '/admin/usuarios'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/carteiras'
    | '/_authenticated/comite'
    | '/_authenticated/dashboard'
    | '/_authenticated/fechar-mes'
    | '/_authenticated/fluxo-de-caixa'
    | '/_authenticated/uploads'
    | '/_authenticated/admin/usuarios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/carteiras': {
      id: '/_authenticated/carteiras'
      path: '/carteiras'
      fullPath: '/carteiras'
      preLoaderRoute: typeof AuthenticatedCarteirasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/comite': {
      id: '/_authenticated/comite'
      path: '/comite'
      fullPath: '/comite'
      preLoaderRoute: typeof AuthenticatedComiteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fechar-mes': {
      id: '/_authenticated/fechar-mes'
      path: '/fechar-mes'
      fullPath: '/fechar-mes'
      preLoaderRoute: typeof AuthenticatedFecharMesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fluxo-de-caixa': {
      id: '/_authenticated/fluxo-de-caixa'
      path: '/fluxo-de-caixa'
      fullPath: '/fluxo-de-caixa'
      preLoaderRoute: typeof AuthenticatedFluxoDeCaixaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/uploads': {
      id: '/_authenticated/uploads'
      path: '/uploads'
      fullPath: '/uploads'
      preLoaderRoute: typeof AuthenticatedUploadsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedCarteirasRoute: typeof AuthenticatedCarteirasRoute
  AuthenticatedComiteRoute: typeof AuthenticatedComiteRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFecharMesRoute: typeof AuthenticatedFecharMesRoute
  AuthenticatedFluxoDeCaixaRoute: typeof AuthenticatedFluxoDeCaixaRoute
  AuthenticatedUploadsRoute: typeof AuthenticatedUploadsRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCarteirasRoute: AuthenticatedCarteirasRoute,
  AuthenticatedComiteRoute: AuthenticatedComiteRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFecharMesRoute: AuthenticatedFecharMesRoute,
  AuthenticatedFluxoDeCaixaRoute: AuthenticatedFluxoDeCaixaRoute,
  AuthenticatedUploadsRoute: AuthenticatedUploadsRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
